from os import system
lista = [
'BRSGSTAGE2M7WUX', 
'BRSGSTAGE2UCGMO',
'BRSGSTAGE3V91HM',
'BRSGSTAGE6YTSBU',
'BRSGSTAGE8INEDM',
'BRSGSTAGEAS1WIB',
'BRSGSTAGEDJWIHP',
'BRSGSTAGEEN26JV',
'BRSGSTAGEEWFZRB',
'BRSGSTAGEFLXSQD',
'BRSGSTAGEIHBUI1',
'BRSGSTAGEKDMPJQ',
'BRSGSTAGELL8FUB',
'BRSGSTAGEN4AXRS',
'BRSGSTAGETBYDEC',
'BRSGSTAGEUOEPMW',
'BRSGSTAGEW7EOJN',
'BRSGSTAGEWLC3WF',
'BRSGSTAGEXEYCEY',
'BRSGSTAGEXKYS3L',
'BRSGSTAGEZWU1RL',]


for i in lista:
	print('=' * 30)
	print(i)
	print('=' * 30)
	print()
	system(f'query user /server:{i}')
	print()
	